[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autogen-mcp-tool-adapter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-core==0.4.0.dev11",
    "mcp>=1.1.2",
]

[tool.uv]
prerelease = "allow"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = [
     "src"
]